require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'app/views/**/*'
    - 'config/environments/*'
    - 'node_modules/**/*'
    - 'config/**/*'

Layout/IndentationConsistency:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
